/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryclient;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.Container;
import java.rmi.RemoteException;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tarana
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    public IssueBook() throws RemoteException {
        Container c = getContentPane();
        c.setBackground(Color.GRAY);
        initComponents();
        printJtable();

    }

    public IssueBook(int id) throws RemoteException {
        this();
        txtbookid.setText(Integer.toHexString(id));
        //txtbookname.setText(bookname);
    }

    public void printJtable() throws RemoteException {
        Client client = new Client();
        //  int k=client.stub.AddBooks(name, category, author, publisher, edition);
        Vector v = new Vector();
        // v=client.stub.TableLoadBooks();
        v = client.stub.TableIssueBookDetails();
        DefaultTableModel d = (DefaultTableModel) table.getModel();
        d.setRowCount(0);
        for (int i = 0; i < v.size(); i++) {
            Vector v1 = new Vector();
            v1 = (Vector) v.get(i);
            d.addRow(v1);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtstdid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtissuedate = new datechooser.beans.DateChooserCombo();
        txtreturndate = new datechooser.beans.DateChooserCombo();
        jLabel8 = new javax.swing.JLabel();
        txtbookid = new javax.swing.JTextField();
        txtissueby = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ISSUE BOOKS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 230, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("STUDENT ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("ISSUED BY ADMIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("RETURN DATE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));
        jPanel1.add(txtstdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 160, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setText("ISSUE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 110, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK ID", "STUDENT ID", "ISSUE DATE", "RETURN DATE", "ISSUEDBY", "ISISSUED"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 780, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryserver/library (3).jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 140, 120));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("ISSUE DATE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));
        jPanel1.add(txtissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 160, 30));
        jPanel1.add(txtreturndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 160, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("BOOK ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));
        jPanel1.add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 160, -1));
        jPanel1.add(txtissueby, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1270, 530));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("LOGOUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String stdid, name, bookname, issuedby,bookid1;
            int bookid;
            // Date issuedate,returndate;
            Client client = new Client();

            stdid = txtstdid.getText();
            // name=txtname.getText();
            bookid1 = txtbookid.getText();
            //  bookname=txtbookname.getText();
            issuedby = txtissueby.getText();
//            System.out.println("hello");
            System.out.println(txtissuedate.getText());
//            SimpleDateFormat f1 = new SimpleDateFormat("dd/MM/yyyy");
//            java.util.Date issuedate = f1.parse(txtissuedate.getText());
//            java.util.Date returndate = f1.parse(txtreturndate.getText());

//            System.out.println(txtissuedate.getText());
//            System.out.println("hello");
            
            if(!(stdid.equals("")||bookid1.equals("")||issuedby.equals("")))
            {      
                bookid = Integer.parseInt(txtbookid.getText());
            int k = client.stub.IssueBooks(stdid, bookid, txtissuedate.getText(), txtreturndate.getText(), issuedby);
            Vector v = new Vector();
            v = client.stub.TableIssueBookDetails();
//            System.out.println("hello3");
            DefaultTableModel d = (DefaultTableModel) table.getModel();
            d.setRowCount(0);
            for (int i = 0; i < v.size(); i++) {
                Vector v1 = new Vector();
                v1 = (Vector) v.get(i);
                d.addRow(v1);
            }
            if (k == 1) {
                JOptionPane.showMessageDialog(this, "Book has been issued succesfully!!");
                txtstdid.setText("");
                //  txtname.setText(" ");
                txtbookid.setText(" ");
                // txtbookname.setText(" ");
                txtissueby.setText(" ");
                txtreturndate.setText("");
                txtissuedate.setText("");
                txtstdid.requestFocus();

            } else if (k == 2) {
                JOptionPane.showMessageDialog(this, "This book already has been issued to this student!!");
                txtstdid.setText("");
                //  txtname.setText(" ");
                txtbookid.setText(" ");
                // txtbookname.setText(" ");
                txtissueby.setText(" ");
                txtreturndate.setText("");
                txtissuedate.setText("");
                txtstdid.requestFocus();
            } else if (k == 3) {
                JOptionPane.showMessageDialog(this, "Issued book limit exceeded!!");
                txtstdid.setText("");
                //  txtname.setText(" ");
                txtbookid.setText(" ");
                // txtbookname.setText(" ");
                txtissueby.setText(" ");
                txtreturndate.setText("");
                txtissuedate.setText("");
                txtstdid.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Error in addition!!");
            }
        } 
            else
              {
             JOptionPane.showMessageDialog(this, "All fields are required!!");   
                }
        }  
            catch (RemoteException ex) {
            System.out.println("err");
            Logger.getLogger(IssueBook.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
//        DefaultTableModel d=(DefaultTableModel)table.getModel();
//        int selectIndex=table.getSelectedRow();
//        int id=Integer.parseInt(d.getValueAt(selectIndex,0).toString());
//        txtstdid.setText(d.getValueAt(selectIndex,1).toString());
//        txtname.setText(d.getValueAt(selectIndex,2).toString());
//        txtauthor.setText(d.getValueAt(selectIndex,3).toString());
//        txtpublisher.setText(d.getValueAt(selectIndex,4).toString());
//        txtedition.setText(d.getValueAt(selectIndex,5).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        AdminPanel a = new AdminPanel();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LoginPage lg = new LoginPage();
        this.setVisible(false);
        lg.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new IssueBook().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(IssueBook.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtissueby;
    private datechooser.beans.DateChooserCombo txtissuedate;
    private datechooser.beans.DateChooserCombo txtreturndate;
    private javax.swing.JTextField txtstdid;
    // End of variables declaration//GEN-END:variables
}
