/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryclient;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tarana
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    public ReturnBook() throws RemoteException {
        Container c=getContentPane();
        c.setBackground(Color.GRAY);
        initComponents();
        printJtable();
        
    }
   
    
    public void printJtable() throws RemoteException
    {
     Client client=new Client();
    //  int k=client.stub.AddBooks(name, category, author, publisher, edition);
              Vector v=new Vector();
             // v=client.stub.TableLoadBooks();
               v=client.stub.TableReturnBookDetails();
              DefaultTableModel d=(DefaultTableModel)table.getModel();
              d.setRowCount(0);
              for(int i=0;i<v.size();i++)
              {
               Vector v1=new Vector();
               v1=(Vector) v.get(i);
               d.addRow(v1);
              }
     
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtstdid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtactreturndate = new datechooser.beans.DateChooserCombo();
        jLabel8 = new javax.swing.JLabel();
        txtbookid = new javax.swing.JTextField();
        txtexceededdays = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfine = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("RETURN BOOKS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 160, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("STUDENT ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("EXCEEDED DAYS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 190, -1));
        jPanel1.add(txtstdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 160, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setText("RETURN BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 160, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK ID", "STUDENT ID", "ACTUALRETURNDATE", "EXCEEDEDDAYS", "FINE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 780, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryserver/library (3).jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 140, 120));
        jPanel1.add(txtactreturndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 160, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("BOOK ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        txtbookid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbookidKeyPressed(evt);
            }
        });
        jPanel1.add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 160, -1));
        jPanel1.add(txtexceededdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 170, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setText("ACTUAL RETURN DATE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, -1));
        jPanel1.add(txtfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("FINE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 60, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 130, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1270, 530));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("LOGOUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String stdid,bookid1;
            int bookid;
            int arr[]=new int[100];
           // Date issuedate,returndate;
             Client client=new Client();
             
          stdid=txtstdid.getText();
          bookid1 = txtbookid.getText();
          if(!(stdid.equals("")||bookid1.equals("")))
          {  
          bookid=Integer.parseInt(txtbookid.getText());
       
        
//          System.out.println("hello");
//           SimpleDateFormat f1=new SimpleDateFormat("dd/MM/yyyy");  
//            
//            java.util.Date returndate= f1.parse(txtactreturndate.getText());
         
            arr=client.stub.ReturnBooks(stdid,bookid,txtactreturndate.getText());
             
            int x=arr[0];
            int y=arr[1];
            System.out.println(x);
            System.out.println(y);
            String l=String.valueOf(x);
            String m=String.valueOf(y);        
            txtexceededdays.setText(l);
            txtfine.setText(m);
          }
          else
              JOptionPane.showMessageDialog(this, "All fields are required!!");
            
        } catch (RemoteException ex) {
            System.out.println("err");
            Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
//        DefaultTableModel d=(DefaultTableModel)table.getModel();
//        int selectIndex=table.getSelectedRow();
//        int id=Integer.parseInt(d.getValueAt(selectIndex,0).toString());
//        txtstdid.setText(d.getValueAt(selectIndex,1).toString());
//        txtname.setText(d.getValueAt(selectIndex,2).toString());
//        txtauthor.setText(d.getValueAt(selectIndex,3).toString());
//        txtpublisher.setText(d.getValueAt(selectIndex,4).toString());
//        txtedition.setText(d.getValueAt(selectIndex,5).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        AdminPanel a=new AdminPanel();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LoginPage lg=new LoginPage();
        this.setVisible(false);
        lg.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtbookidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbookidKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {  
            Date arr[]=new Date[10];
            String stdid=txtstdid.getText();
            int bookid=Integer.parseInt(txtbookid.getText());
            Client client=new Client();
            try {
                arr=(Date[]) client.stub.FetchData(stdid,bookid);
            } catch (RemoteException ex) {
                Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
            }
           
           java.util.Date issuedate=arr[0];
           java.util.Date returndate=arr[1];
           DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss");  
           String isuueDate = dateFormat.format(issuedate);  
           String returnDate=dateFormat.format(returndate);
          // txtissuedate.setText(isuueDate);
           //txtexpreturndate.setText(returnDate);
           
        }
    }//GEN-LAST:event_txtbookidKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //TODO: submit fine and update book count
        int bookId= Integer.parseInt(txtbookid.getText());
        String stdId=txtstdid.getText();
        String actualreturn=txtactreturndate.getText();
        String exceededdays=txtexceededdays.getText();
        String fine=txtfine.getText();
       
        Client cl = new Client();
        try {
            Vector v=new Vector();
           // if(!(exceededdays.equals("")||fine.equals("")))
           // {
            int k=cl.stub.submitReturnBookDetails(bookId,stdId,actualreturn,exceededdays,fine);
             v=cl.stub.TableReturnBookDetails();
               DefaultTableModel d = (DefaultTableModel) table.getModel();
            d.setRowCount(0);
            for (int i = 0; i < v.size(); i++) {
                Vector v1 = new Vector();
                v1 = (Vector) v.get(i);
                d.addRow(v1);
            }
            
            cl.stub.SendEmailIfUserHasRequestedForSameBook(bookId);
            if(k>0)
            {
              JOptionPane.showMessageDialog(this, "Book has been returned succesfully!!");
            }
            
           // }
            //else
              //  JOptionPane.showMessageDialog(this, "All fields are required!!");
                
        } catch (RemoteException ex) {
            Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
                txtstdid.setText(" ");
                txtbookid.setText(" ");
                txtexceededdays.setText(" ");
                txtfine.setText(" ");
               
                txtstdid.requestFocus();
                 JOptionPane.showMessageDialog(this,"Record has been cleared!!!");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReturnBook().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private datechooser.beans.DateChooserCombo txtactreturndate;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtexceededdays;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtstdid;
    // End of variables declaration//GEN-END:variables
}
