/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryclient;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.Container;
import java.rmi.RemoteException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tarana
 */
public class StudentDetail extends javax.swing.JFrame {

    /**
     * Creates new form ManageBooks
     */
    public StudentDetail() throws RemoteException {
        Container c=getContentPane();
        c.setBackground(Color.GRAY);
        initComponents();
        printJtable();
        
    }
    public void printJtable() throws RemoteException
    {
     Client client=new Client();
    //  int k=client.stub.AddBooks(name, category, author, publisher, edition);
              Vector v=new Vector();
              v=client.stub.TableLoadStudents();
              DefaultTableModel d=(DefaultTableModel)table.getModel();
              d.setRowCount(0);
        //  int m=v.size();
          //    System.out.print(m);    
              for(int i=0;i<v.size();i++)
              {
               Vector v1=new Vector();
               v1=(Vector) v.get(i);
               d.addRow(v1);
              }
     
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtstdid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtphoneno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaddr = new javax.swing.JTextArea();
        show_validation = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MANAGE STUDENTS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 230, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("STUDENT ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("EMAIL-ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("ADDRESS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        txtstdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdidActionPerformed(evt);
            }
        });
        jPanel1.add(txtstdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 160, -1));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 160, -1));

        txtphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtphonenoKeyPressed(evt);
            }
        });
        jPanel1.add(txtphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 160, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 110, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 110, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT ID", "NAME", "PHONE NO", "ADDRESS", "EMAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 31, 520, 450));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryserver/library (3).jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 140, 120));

        txtaddr.setColumns(20);
        txtaddr.setRows(5);
        jScrollPane2.setViewportView(txtaddr);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        show_validation.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(show_validation, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 160, 20));

        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("PHONE NO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1030, 500));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("LOGOUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String name,stdid,addr,email;
            String phoneno;
             Client client=new Client();
             
            stdid=txtstdid.getText();
            name=txtname.getText();
            phoneno=txtphoneno.getText();
            addr=txtaddr.getText();
            email=txtemail.getText();
            //edition=txtedition.getText();
            if(!(name.equals("")||stdid.equals("")||phoneno.equals("")||addr.equals("")||email.equals("")))
            {      
            int k=client.stub.AddStudents(stdid,name,phoneno,addr,email);
              Vector v=new Vector();
              v=client.stub.TableLoadStudents();
              DefaultTableModel d=(DefaultTableModel)table.getModel();
              d.setRowCount(0);
              for(int i=0;i<v.size();i++)
              {
               Vector v1=new Vector();
               v1=(Vector) v.get(i);
               d.addRow(v1);
              }
            if(k>0)
            {
                JOptionPane.showMessageDialog(this,"Record of student succesfully added!!");
                txtstdid.setText("");
                txtphoneno.setText("");
               txtaddr.setText(" ");
                //txtedition.setText(" ");
                txtname.setText(" ");
                txtemail.setText(" ");
                txtstdid.requestFocus();
                
            }
            else
            {
               JOptionPane.showMessageDialog(this,"Error in addition!!"); 
            }
            
            }
            else
                JOptionPane.showMessageDialog(this,"All fields are required to be filled!!"); 
        } catch (RemoteException ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel d=(DefaultTableModel)table.getModel();
        int selectIndex=table.getSelectedRow();
      //  int id=Integer.parseInt(d.getValueAt(selectIndex,0).toString());
        txtstdid.setText(d.getValueAt(selectIndex,0).toString());
        txtname.setText(d.getValueAt(selectIndex,1).toString());
        txtphoneno.setText(d.getValueAt(selectIndex,2).toString());
        txtaddr.setText(d.getValueAt(selectIndex,3).toString());
       txtemail.setText(d.getValueAt(selectIndex,4).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
        String name,stdid,addr,email;
        String phoneno;
        DefaultTableModel d1=(DefaultTableModel)table.getModel();
         Client client=new Client();
       
            
            stdid=txtstdid.getText(); 
            name=txtname.getText();
           phoneno=txtphoneno.getText();
           addr=txtaddr.getText();
           email=txtemail.getText();
            //edition=txtedition.getText();
            
            int k=client.stub.UpdateStudentRecord(name,addr,phoneno,stdid,email);
             Vector v=new Vector();
              v=client.stub.TableLoadStudents();
              DefaultTableModel d=(DefaultTableModel)table.getModel();
              d.setRowCount(0);
              for(int i=0;i<v.size();i++)
              {
               Vector v1=new Vector();
               v1=(Vector) v.get(i);
               d.addRow(v1);
              }
            if(k>0)
            {
                JOptionPane.showMessageDialog(this,"Record of student has been Updated!!!");
                txtstdid.setText(" ");
                txtphoneno.setText(" ");
              //  txtpublisher.setText(" ");
                txtemail.setText(" ");
                txtaddr.setText(" ");
                txtname.setText(" ");
                
                txtstdid.requestFocus();
                
            }
            else
            {
               JOptionPane.showMessageDialog(this,"Error in Updation!!"); 
            }
        } catch (RemoteException ex) {
            System.out.println("err");
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try
        {
        String name,stdid;
        DefaultTableModel d1=(DefaultTableModel)table.getModel();
         Client client=new Client();
      //  int selectIndex=table.getSelectedRow();
        //int id=Integer.parseInt(d1.getValueAt(selectIndex,0).toString());
       stdid=txtstdid.getText();
          
            int k=client.stub.DelelteStudentRecord(stdid);
             Vector v=new Vector();
              v=client.stub.TableLoadStudents();
              DefaultTableModel d=(DefaultTableModel)table.getModel();
              d.setRowCount(0);
              for(int i=0;i<v.size();i++)
              {
               Vector v1=new Vector();
               v1=(Vector) v.get(i);
               d.addRow(v1);
              }
            if(k>0)
            {
                JOptionPane.showMessageDialog(this,"Record of the student has been Deleted!!!");
                txtstdid.setText("");
                txtphoneno.setText(" ");
                txtaddr.setText(" ");
               txtemail.setText(" ");
                txtname.setText(" ");
                
                txtstdid.requestFocus();
                
            }
            else
            {
               JOptionPane.showMessageDialog(this,"Error in Deletion!!"); 
            }
        } catch (RemoteException ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        AdminPanel a=new AdminPanel();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LoginPage lg=new LoginPage();
        this.setVisible(false);
        lg.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtphonenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphonenoKeyPressed
        // TODO add your handling code here:
       // try{
         //  int i=Integer.parseInt(txtphoneno.getText());
           //show_validation.setText("");
        //}
        //catch(NumberFormatException e)
        //{
          // show_validation.setText("Invalid no");
        //}
    }//GEN-LAST:event_txtphonenoKeyPressed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyPressed

    private void txtstdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StudentDetail().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel show_validation;
    private javax.swing.JTable table;
    private javax.swing.JTextArea txtaddr;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtstdid;
    // End of variables declaration//GEN-END:variables
}
